{{- define "ioc-chart.deployment" -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Chart.Name }}
    beamline: {{ .Values.beamline }}
    ioc_version: {{ .Chart.AppVersion }}
    is_ioc: "True"
  annotations:
    kubernetes.io/change-cause: {{ .Chart.AppVersion }} deployed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        beamline: {{ .Values.beamline }}
        ioc_version: {{ .Chart.AppVersion }}
        is_ioc: "True"
    spec:
      serviceAccountName: epics-iocs-priv
      hostNetwork: true
      terminationGracePeriodSeconds: 5 # nice to have quick restarts on IOCs
      volumes:
        {{- if .Values.autosave -}}
        - name: {{ .Chart.Name }}
          persistentVolumeClaim:
            claimName: {{ .Chart.Name }}
        {{- end }}
        - name: config-volume
          configMap:
            name: {{ .Chart.Name }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          allowPrivilegeEscalation: false
        image: {{ .Values.base_image }}
        command:
          - bash
        args:
          - {{ .Values.iocFolder }}/config/start.sh
        volumeMounts:
        - name: config-volume
          mountPath: {{ .Values.iocFolder }}/config
        {{- if .Values.autosave -}}
        - name: {{ .Chart.Name }}
          mountPath: /autosave
        {{- end }}
        stdin: true
        tty: true
        resources:
          limits:
            memory: {{ .Values.memory | default "512Mi" | quote }}
            cpu: {{ .Values.cpu | default "1" | quote }}
          requests:
            memory: "512Mi"
            cpu: "1"
        imagePullPolicy: Always
        env:
        - name: IOCSH_PS1
          value: "{{ .Chart.Name }} > "
        - name: IOC_NAME
          value: {{ .Chart.Name }}
        - name: IOC_VERSION
          value: {{ .Chart.AppVersion }}
      {{- if .Values.useAffinity }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: beamline
                operator: In
                values:
                  - {{ .Values.beamline }}
      {{- end }}
      tolerations:
        - key: nodetype
          operator: Equal
          value: {{ .Values.beamline }}
          effect: NoSchedule


{{ end }}