name:  Build and publish a beamline's ioc helm charts

on:
  push:
  pull_request:

env:
  HELM_VERSION_TO_INSTALL: 3.8.2 # version of HELM to install

jobs:
  build-and-push-helm-charts:
    name: publish helm charts to ghcr.io
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: push the helm chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin

          # only publish if this is a tagged releasse
          if [[ ${GITHUB_REF} = refs/tags/* ]] ; then

            TAG=${GITHUB_REF#refs/tags/}

            # Update all chart dependencies.
            helm dependency update .

            # update the helm chart versions with the tag
            sed -e "s/^version: .*$/version: ${TAG}/g" -e "s/^appVersion: .*$/appVersion: ${TAG}/g" -i Chart.yaml

            for THIS_TAG in latest ${TAG}
            do
                URL="ghcr.io/${{github.repository}}:${THIS_TAG}"
                echo saving chart to "${URL}" ...
                helm chart save . "${URL}"
                echo push to "${URL}" ...
                helm chart push "${URL}"
            done

          fi