name: Build and publish a beamline's ioc helm charts

on:
  push:
  pull_request:

env:
  HELM_VERSION_TO_INSTALL: 3.8.2 # version of HELM to install

jobs:
  build-and-push-helm-charts:
    name: publish helm charts to ghcr.io
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install helm
        uses: Azure/setup-helm@v1
        with:
          version: ${{ env.HELM_VERSION_TO_INSTALL }}

      - name: push the helm chart
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io/${{ github.repository_owner }} --username ${{ github.repository_owner }} --password-stdin

          REGISTRY=oci://ghcr.io/epics-containers

          # helm tags must be SemVar. Use 0.0.0-b0 for testing the latest not tagged build
          if [ "${GITHUB_REF_TYPE}" == "tag" ] ; then
            TAG=${GITHUB_REF_NAME}
          else
            TAG="1.0.0-b0"
          fi
          NAME=$(awk '/name:/{print $NF}' Chart.yaml)

          # update the helm chart versions with the tag
          echo updating Chart version to ${TAG}
          sed -e "s/^version: .*$/version: ${TAG}/g" -e "s/^appVersion: .*$/appVersion: ${TAG}/g" -i Chart.yaml

          # Update all chart dependencies.
          helm dependency update .
          helm package .
          package=${NAME}-${TAG}.tgz

          helm push "$package" $REGISTRY
